// ponytail: shrink — keys ARE the codes, no need for redundant code field
export const ErrorCodes = {
  AUTH_001: 'auth.error.invalidCredentials',
  AUTH_002: 'auth.error.tokenExpired',
  AUTH_003: 'auth.error.accountLocked',
  USER_001: 'users.error.emailExists',
  USER_002: 'users.error.notInOrganization',
  PRODUCT_001: 'products.error.codeDuplicate',
  PRODUCT_002: 'products.error.hasSales',
  CUSTOMER_001: 'customers.error.rifExists',
  SALE_001: 'sales.error.issuedImmutable',
  SALE_002: 'sales.error.notFound',
  SALE_003: 'sales.error.noItems',
  SALE_004: 'sales.error.creditNeedsCustomer',
  SALE_005: 'sales.error.insufficientStock',
  PO_001: 'purchaseOrders.error.receivedImmutable',
  PO_002: 'purchaseOrders.error.notFound',
  PO_003: 'purchaseOrders.error.alreadyReceived',
  PO_004: 'purchaseOrders.error.notWithholdingAgent',
  PO_005: 'purchaseOrders.error.missingWithholdingPct',
  PO_006: 'purchaseOrders.error.missingWithholdingProof',
  PO_007: 'purchaseOrders.error.detailNotFound',
  PO_008: 'purchaseOrders.error.quantityExceeded',
  TAX_001: 'taxes.error.withholdingAlreadyApplied',
  TAX_002: 'taxes.error.withholdingExceedsLimit',
  ACCT_001: 'accounting.error.unbalanced',
  ACCT_002: 'accounting.error.periodClosed',
} as const;

export type ErrorCode = keyof typeof ErrorCodes;
